version: 2

models:
  - name: stablecoin_activity_per_day
    config:
      contract:
        enforced: true # Model protected by contract
    columns:
      - name: date
        data_type: date

      - name: token_address
        data_type: varchar

      - name: type
        data_type: varchar

      - name: symbol
        data_type: varchar

      - name: total_usd_value
        data_type: float

