version: 2

sources:
  - name: eth
    database: "eth"
    schema: "eth_schema"
    description: "{{ doc('eth_source') }}"
    tables:
      - name: contracts
        description: "{{ doc('eth_contracts') }}"
        columns:
          - name: address
          - name: block_hash
          - name: block_number
          - name: block_timestamp
          - name: bytecode
          - name: date
          - name: last_modified

      - name: token_transfers
        description: "{{ doc('eth_token_transfers') }}"
        columns:
          - name: block_hash
          - name: block_number
          - name: block_timestamp
          - name: date
          - name: from_address
          - name: to_address
          - name: last_modified
          - name: log_index
          - name: token_address
          - name: transaction_hash
          - name: value

      - name: transactions
        description: "{{ doc('eth_transactions') }}"
        columns:
          - name: block_hash
          - name: block_number
          - name: block_timestamp
          - name: date
          - name: from_address
          - name: gas
          - name: gas_price
          - name: hash
          - name: input
          - name: last_modified
          - name: max_fee_per_gas
          - name: max_priority_fee_per_gas
          - name: nonce
          - name: receipt_contract_address
          - name: receipt_cumulative_gas_used
          - name: receipt_effective_gas_price
          - name: receipt_gas_used
          - name: receipt_status
          - name: to_address
          - name: transaction_index
          - name: transaction_type
          - name: value

      - name: contracts_clone
        description: "{{ doc('eth_contracts_clone') }}"